import { useState } from "react";
import Flashcard from "./Flashcard";

export default function FlashcardCarousel() {
  const flashcards = [
    {
      question: "What is React?",
      answer: "A JavaScript library for building user interfaces.",
    },
    {
      question: "What is a component?",
      answer: "A reusable piece of code that represents a part of the UI.",
    },
    {
      question: "Explain the concept of Virtual DOM in React.",
      answer:
        "The Virtual DOM is an in-memory representation of the real DOM elements generated by React components. It is a lightweight copy of the actual DOM that React uses to optimize updates and rendering.",
    },
  ];

  const [currentIndex, setCurrentIndex] = useState(0);
  const [showAnswer, setShowAnswer] = useState(false);

  const handleNext = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % flashcards.length);
    setShowAnswer(false); // Reset to question side
  };

  const handlePrevious = () => {
    setCurrentIndex(
      (prevIndex) => (prevIndex - 1 + flashcards.length) % flashcards.length
    );
    setShowAnswer(false); // Reset to question side
  };

  const toggleCard = () => {
    setShowAnswer(!showAnswer);
  };

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-100 dark:bg-gray-900">
      <div
        onClick={toggleCard}
        className="cursor-pointer w-80 h-96 mx-auto p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 ease-in-out dark:bg-gray-800 dark:text-white flex flex-col justify-center"
      >
        <div className="text-center overflow-y-auto">
          <h3 className="text-lg font-semibold mb-4">
            {showAnswer ? "Answer" : "Question"}
          </h3>
          <p className="text-gray-700 dark:text-gray-300">
            {showAnswer
              ? flashcards[currentIndex].answer
              : flashcards[currentIndex].question}
          </p>
        </div>
      </div>
      <div className="mt-4 flex space-x-4">
        <button
          onClick={handlePrevious}
          className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-300"
        >
          Previous
        </button>
        <button
          onClick={handleNext}
          className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-300"
        >
          Next
        </button>
      </div>
    </div>
  );
}
